# first create secret
# echo -n "DB_USERNAME" > db.username
# echo -n "DB_PASSWORD" > db.password
# kubectl create secret generic --from-file=db.username --from-file=db.password db-secret
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-backend
  labels:
    app: backend
    env: dev
spec:
  selector:
    matchLabels:
      app: backend
      env: dev
  replicas: 1
  template:
    metadata:
      name: storage-backend
      labels:
        app: backend
        env: dev
    spec:
      restartPolicy: Always
      containers:
      - name: storage-backend
        image: daocloud.io/alaien/storage
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: db.username
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db.username
        - name: db.password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db.password
        command: ["java","-jar","-Dspring.profiles.active=dev","storage-backend.jar"]
      volumes:
      - name: db-secret
        secret:
          secretName: db-secret
---

apiVersion: v1
kind: Service
metadata:
  name: storage-backend
  labels:
    app: backend
    env: dev
spec:
  selector:
    app: backend
    env: dev
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 8000